packages: []

overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/types': ^8.38.0
  '@typescript-eslint/utils': ^8.38.0
  eslint: ^9.38.0
  tsx: ^4.20.6
catalogs:
  dev:
    '@eslint/config-inspector': ^1.3.0
    '@king-3/prettier-config': ^3.3.0
    '@prettier/plugin-oxc': ^0.0.5
    '@types/node': ^24.10.0
    ansis: ^4.2.0
    bumpp: ^10.3.1
    eslint-typegen: ^2.3.0
    jiti: ^2.6.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    tsdown: ^0.16.5
    tsx: ^4.20.6
    typescript: ^5.9.3
  parsers:
    '@typescript-eslint/parser': ^8.46.3
    jsonc-eslint-parser: ^2.4.1
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.0
  peer:
    '@eslint-react/eslint-plugin': ^2.0.1
    '@next/eslint-plugin-next': ^16.0.1
    '@unocss/eslint-plugin': ^66.5.4
    eslint: ^9.38.0
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@typescript-eslint/eslint-plugin': ^8.46.3
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^61.1.12
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.3.0
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-vue: ^10.5.1
    eslint-plugin-yml: ^1.19.0
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint/js': ^9.38.0
    '@eslint/markdown': ^7.5.0
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-flat-config-utils: ^2.1.4
    globals: ^16.5.0
    local-pkg: ^1.1.2
    prettier: ^3.6.2
