packages: []

overrides:
  '@eslint-community/eslint-utils': ^4.7.0
  '@typescript-eslint/types': ^8.38.0
  '@typescript-eslint/utils': ^8.38.0
  eslint: ^9.32.0
  tsx: ^4.20.3

catalogs:
  dev:
    '@eslint/config-inspector': ^1.1.0
    '@king-3/prettier-config': ^1.0.0
    '@types/node': ^24.1.0
    ansis: ^4.1.0
    bumpp: ^10.2.0
    eslint-typegen: ^2.3.0
    tsdown: ^0.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3

  parsers:
    '@typescript-eslint/parser': ^8.38.0
    jsonc-eslint-parser: ^2.4.0
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.0

  peer:
    '@eslint-react/eslint-plugin': ^1.52.5
    '@next/eslint-plugin-next': ^15.5.3
    '@unocss/eslint-plugin': ^66.3.3
    eslint: ^9.32.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20

  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@typescript-eslint/eslint-plugin': ^8.38.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^51.4.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.21.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.1.0
    eslint-plugin-prettier: ^5.5.3
    eslint-plugin-regexp: ^2.9.0
    eslint-plugin-unicorn: ^60.0.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.3.0
    eslint-plugin-yml: ^1.18.0
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint/js': ^9.32.0
    '@eslint/markdown': ^7.1.0
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-flat-config-utils: ^2.1.0
    globals: ^16.3.0
    local-pkg: ^1.1.1
    prettier: ^3.6.2
