shellEmulator: true

trustPolicy: no-downgrade

packages: []

catalogs:
  dev:
    '@eslint/config-inspector': ^2.0.0
    '@king-3/prettier-config': ^3.4.0
    '@types/node': ^25.6.0
    ansis: ^4.2.0
    baseline-browser-mapping: ^2.10.18
    bumpp: ^11.0.1
    eslint-typegen: ^2.3.1
    jiti: ^2.6.1
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
    tsdown: ^0.21.7
    tsx: ^4.21.0
    typescript: ^6.0.2
  parsers:
    '@typescript-eslint/parser': ^8.58.1
    vue-eslint-parser: ^10.4.0
    yaml-eslint-parser: ^2.0.0
  peer:
    '@eslint-community/eslint-utils': ^4.9.1
    '@eslint-react/eslint-plugin': ^3.0.0
    '@next/eslint-plugin-next': ^16.2.3
    '@typescript-eslint/types': ^8.58.1
    '@typescript-eslint/utils': ^8.58.1
    '@unocss/eslint-plugin': ^66.6.8
    eslint: ^10.2.0
    eslint-plugin-react-refresh: ^0.5.2
    synckit: ^0.11.12
  plugins:
    '@e18e/eslint-plugin': ^0.3.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.7.1
    '@typescript-eslint/eslint-plugin': ^8.58.1
    eslint-plugin-antfu: ^3.2.2
    eslint-plugin-command: ^3.5.2
    eslint-plugin-import-lite: ^0.6.0
    eslint-plugin-jsdoc: ^62.9.0
    eslint-plugin-jsonc: ^3.1.2
    eslint-plugin-n: ^17.24.0
    eslint-plugin-perfectionist: ^5.8.0
    eslint-plugin-pnpm: ^1.6.0
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-regexp: ^3.1.0
    eslint-plugin-unicorn: ^64.0.0
    eslint-plugin-unused-imports: ^4.4.1
    eslint-plugin-vue: ^10.8.0
    eslint-plugin-yml: ^3.3.1
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^1.2.0
    '@eslint/js': ^10.0.1
    '@eslint/markdown': ^8.0.1
    eslint-config-flat-gitignore: ^2.3.0
    eslint-config-prettier: ^10.1.8
    eslint-flat-config-utils: ^3.1.0
    find-up-simple: ^1.0.1
    globals: ^17.5.0
    local-pkg: ^1.1.2
    prettier: ^3.8.1
