minimumReleaseAgeExclude:
  - '@king3/prettier-config@2.1.0'

shellEmulator: true

trustPolicy: no-downgrade

packages: []

catalogs:
  dev:
    '@eslint/config-inspector': ^3.1.0
    '@king3/prettier-config': ^2.1.0
    '@types/node': ^26.1.1
    baseline-browser-mapping: ^2.10.44
    bumpp: ^11.1.0
    eslint-typegen: ^2.3.1
    jiti: ^2.7.0
    lint-staged: ^17.1.0
    prettier: ^3.9.6
    simple-git-hooks: ^2.13.1
    tsdown: ^0.22.12
    tsx: ^4.23.1
    typescript: ^6.0.3
  parsers:
    '@typescript-eslint/parser': ^8.65.0
    vue-eslint-parser: ^10.4.1
    yaml-eslint-parser: ^2.1.0
  peer:
    '@eslint-react/eslint-plugin': ^5.17.3
    '@next/eslint-plugin-next': ^16.2.10
    '@unocss/eslint-plugin': ^66.7.5
    eslint: ^10.7.0
    eslint-plugin-react-refresh: ^0.5.3
  plugins:
    '@e18e/eslint-plugin': ^0.5.1
    '@eslint-community/eslint-plugin-eslint-comments': ^4.7.2
    '@typescript-eslint/eslint-plugin': ^8.65.0
    eslint-plugin-antfu: ^3.2.3
    eslint-plugin-command: ^3.5.3
    eslint-plugin-import-lite: ^0.6.0
    eslint-plugin-jsdoc: ^63.2.0
    eslint-plugin-jsonc: ^3.3.0
    eslint-plugin-n: ^18.2.2
    eslint-plugin-perfectionist: ^5.10.0
    eslint-plugin-pnpm: ^1.6.1
    eslint-plugin-prettier: ^5.5.6
    eslint-plugin-regexp: ^3.1.1
    eslint-plugin-unicorn: ^72.0.0
    eslint-plugin-unused-imports: ^4.4.1
    eslint-plugin-vue: ^10.10.0
    eslint-plugin-yml: ^3.6.0
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^1.7.0
    '@eslint/js': ^10.0.1
    '@eslint/markdown': ^8.0.3
    eslint-config-flat-gitignore: ^2.3.0
    eslint-config-prettier: ^10.1.8
    eslint-flat-config-utils: ^3.2.0
    eslint-merge-processors: ^2.0.0
    eslint-processor-vue-blocks: ^2.0.0
    find-up-simple: ^1.0.1
    globals: ^17.7.0
    local-pkg: ^1.2.1

allowBuilds:
  esbuild: true
  simple-git-hooks: true
